version: "3"

services:
  app:
    build: .
    depends_on:
      - mysql
    tty: true
    ports:
      - "8080:8080"
    networks:
      - go_api_network
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
    networks:
      - go_api_network

networks:
  go_api_network:
